### ISSUE TITLE
notification.close()

### ISSUE THREAD

**Issue by artpolikarpov** [chatr/desktop#18]
We need this method to actually do something!

**Comment by Aluxian** [comment]
Done https://github.com/chatr/desktop/commit/471fbfcc8f0022a1cdf6425f0e671485635acf90

Please build and test this (and the other issues).

**Comment by artpolikarpov** [comment]
good!

**Comment by artpolikarpov** [comment]
Hmm, got error.

This is happens, when you close notification, and visitor send one more message. Looks like app trying to remove non-existent notification.

<img width="912" alt="screen shot 2016-03-31 at 14 05 12" src="https://cloud.githubusercontent.com/assets/870859/14173906/9ab5e844-f749-11e5-945a-570482a0445b.png">

To see such logs, you’ll need to `webView.openDevTools()` and in app’s console `console.log = console.info`.

**Comment by Aluxian** [comment]
Yeah, it seems so. Consider it fixed.

**Comment by Aluxian** [comment]
https://github.com/chatr/desktop/commit/cf47060fb0bd630b6a6d61522b74b39b5a8fde71

**Comment by artpolikarpov** [comment]
fixed
