### ISSUE TITLE
Doubling notification sounds

### ISSUE THREAD

**Issue by wilddeer** [chatr/desktop#21]
There's a default notification sound in Win 10 (and Win 8, I assume) that plays alongside with the sound set in Chatra settings. Is there a way to disable the default notification sound?

**Comment by Aluxian** [comment]
Try this:

```
new Notification(title, {
    silent: true
});
```

**Comment by artpolikarpov** [comment]
@Aluxian, I’m afraid we can’t try this. Can we disable default sound on your side?

**Comment by Aluxian** [comment]
Sure, I'll make the app set it.

**Comment by Aluxian** [comment]
https://github.com/chatr/desktop/commit/f96b7a88ee2e638a1591c7f13a4707ad2a69f9a7
