### ISSUE TITLE
Doubling replies

### ISSUE THREAD

**Issue by artpolikarpov** [chatr/desktop#23]
Send 3 messages from visitor side, and then answer to 3d one from notification on OS X (via reply button), callback will be called 3 times!

**Comment by Aluxian** [comment]
Hmm. I think it's because the callback is set using the title instead of the identifier. Nice catch.

**Comment by Aluxian** [comment]
https://github.com/chatr/desktop/commit/f9992af3e6bab0ff657c503b85ffe97b3d5188a5

**Comment by artpolikarpov** [comment]
No immediate reply not woking at all :/

**Comment by Aluxian** [comment]
I will test/debug it tomorrow.

**Comment by artpolikarpov** [comment]
mkay )

**Comment by Aluxian** [comment]
Fixed: https://github.com/chatr/desktop/commit/881dd5f6256bd6774747db8248ec3e8b8bc6ba5d
