### ISSUE TITLE
Looks like auto-correct spelling mistakes does nothing

### ISSUE THREAD

**Issue by artpolikarpov** [chatr/desktop#24]
If so, better to hide it from menu.

**Comment by Aluxian** [comment]
I asked about it here: https://github.com/atom/electron/issues/4371

**Comment by artpolikarpov** [comment]
Let’s hide it!

**Comment by Aluxian** [comment]
https://github.com/chatr/desktop/commit/a1b91160450f5fb03b782744d01623400f3eec97
