### ISSUE TITLE
Error while cheking for updates

### ISSUE THREAD

**Issue by artpolikarpov** [chatr/desktop#25]
Installed v2.0.0, then released v2.0.1, then checked for updated via app:

<img width="532" alt="screen shot 2016-03-31 at 19 54 29" src="https://cloud.githubusercontent.com/assets/870859/14183743/79d5503e-f77a-11e5-8be5-e91e8ddfae5b.png">

Updates server (http://squirrel-updates.chatra.io:3000/) works normally and return this:

{"status":"online","user":"chatr","repo":"desktop","generatedAt":"2016-03-31T16:54:23.477Z","latest":{"id":2926361,"name":"v2.0.1","tag_name":"v2.0.1","published_at":"2016-03-31T16:54:01Z","body":"","assets":[{"id":1494315,"name":"chatra-2.0.1-delta.nupkg","content_type":"application/octet-stream","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-delta.nupkg"},{"id":1494316,"name":"chatra-2.0.1-full.nupkg","content_type":"application/octet-stream","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-full.nupkg"},{"id":1494320,"name":"chatra-2.0.1-osx.dmg","content_type":"application/x-apple-diskimage","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-osx.dmg"},{"id":1494317,"name":"chatra-2.0.1-win32-setup.exe","content_type":"application/x-msdownload","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-win32-setup.exe"},{"id":1494318,"name":"RELEASES","content_type":"application/octet-stream","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/RELEASES"}]}}

**Comment by Aluxian** [comment]
What does it say in the logs?

```
export DEBUG="chatra:*"
./Chatra.app/Contents/MacOS/Chatra
```


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Thu, Mar 31, 2016 at 7:58 PM, Artem Polikarpov < notifications@github.com [notifications@github.com] > wrote:
Installed v2.0.0, then released v2.0.1, then checked for updated via app:

[https://cloud.githubusercontent.com/assets/870859/14183743/79d5503e-f77a-11e5-8be5-e91e8ddfae5b.png]

Updates server ( http://squirrel-updates.chatra.io:3000/ [http://squirrel-updates.chatra.io:3000/] ) works normally and return this:

{"status":"online","user":"chatr","repo":"desktop","generatedAt":"2016-03-31T16:54:23.477Z","latest":{"id":2926361,"name":"v2.0.1","tag_name":"v2.0.1","published_at":"2016-03-31T16:54:01Z","body":"","assets":[{"id":1494315,"name":"chatra-2.0.1-delta.nupkg","content_type":"application/octet-stream","browser_download_url":" https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-delta.nupkg"},{"id":1494316,"name":"chatra-2.0.1-full.nupkg","content_type":"application/octet-stream","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-full.nupkg"},{"id":1494320,"name":"chatra-2.0.1-osx.dmg","content_type":"application/x-apple-diskimage","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-osx.dmg"},{"id":1494317,"name":"chatra-2.0.1-win32-setup.exe","content_type":"application/x-msdownload","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-win32-setup.ex e"},{"id":1494318,"name":"RELEASES","content_type":"application/octet-stream","browser_download_url":"https://github.com/chatr/desktop/releases/download/v2.0.1/RELEASES [https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-delta.nupkg%22%7D,%7B%22id%22:1494316,%22name%22:%22chatra-2.0.1-full.nupkg%22,%22content_type%22:%22application/octet-stream%22,%22browser_download_url%22:%22https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-full.nupkg%22%7D,%7B%22id%22:1494320,%22name%22:%22chatra-2.0.1-osx.dmg%22,%22content_type%22:%22application/x-apple-diskimage%22,%22browser_download_url%22:%22https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-osx.dmg%22%7D,%7B%22id%22:1494317,%22name%22:%22chatra-2.0.1-win32-setup.exe%22,%22content_type%22:%22application/x-msdownload%22,% 22browser_download_url%22:%22https://github.com/chatr/desktop/releases/download/v2.0.1/chatra-2.0.1-win32-setup.exe%22%7D,%7B%22id%22:1494318,%22name%22:%22RELEASES%22,%22content_type%22:%22application/octet-stream%22,%22browser_download_url%22:%22https://github.com/chatr/desktop/releases/download/v2.0.1/RELEASES] "}]}}

**Comment by artpolikarpov** [comment]
I dont know :/

**Comment by Aluxian** [comment]
This is what it should look like:

![image](https://cloud.githubusercontent.com/assets/1418870/14184112/43f57596-f77c-11e5-9517-84e0092412ab.png)

**Comment by Aluxian** [comment]
You can either paste what's in the console or send me the log file (see "saving logs to..." in the screenshot).

**Comment by artpolikarpov** [comment]
When it was only 2.0.0 release on Github, app was answering: "you re up to date".

About what logs you are talking?

**Comment by Aluxian** [comment]
When you run the app on OS X, it logs everything it does in DEBUG mode.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Thu, Mar 31, 2016 at 8:12 PM, Artem Polikarpov < notifications@github.com [notifications@github.com] > wrote:
When it was only 2.0.0 release on Github, app was answering: "you re up to date".

About what logs you are talking?—
