### ISSUE TITLE
Add cleaner for the old Chatra app

### ISSUE THREAD

**Issue by Aluxian** [chatr/desktop#26]

**Comment by artpolikarpov** [comment]
Users says that after clicking «remove» application stop responding. And one user sad that after killing the proccess she has lost a few files from her desktop :/

Did you test it by yourself?

**Comment by Aluxian** [comment]
I did test it in Whatsie first, it didn't delete anything from me. I'll look into it.

**Comment by Aluxian** [comment]
Proposed PR: https://github.com/chatr/desktop/pull/31
