### ISSUE TITLE
Click on notification doesn’t open the app if it was hidden

### ISSUE THREAD

**Issue by artpolikarpov** [chatr/desktop#27]
If the app is not hidden, click on notification works nice (focus the app, redirect to chat). BUT if the app is hidden, click does nothing.

That happens on Mac, can you test what on Win?

**Comment by Aluxian** [comment]
https://github.com/chatr/desktop/commit/cb32dc0cf3f2a2aaf7a83babc0c86a78f5e59cfe

On Windows, the line of code that I added is already being called, so it works (I've just tested).
